---
image:
  - Visual Studio 2022

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python39-x64"
    - PYTHON: "C:\\Python310-x64"

install:
  - "%PYTHON%/python.exe -m pip install -U tox pip setuptools"

build: off

test_script:
  - "%PYTHON%/python.exe -m tox -e appveyor"
